<?php

namespace App\Modules\PP\Controllers;

use App\Http\Controllers\Controller;
use App\Modules\PP\Models\PlannedOrder;
use App\Modules\PP\Services\MrpService;
use App\Modules\PP\Services\PlannedOrderService;
use App\Shared\Helpers\TableQuery;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;
use Inertia\Response;

/** PP_SPECS.md §3D Planned Orders (read-mostly — system-generated by MrpService::run()) + release. */
class PlannedOrderController extends Controller
{
    private const SORTABLE = ['need_by_date', 'qty', 'created_at'];

    public function __construct(
        protected MrpService $mrp,
        protected PlannedOrderService $releaseService,
    ) {}

    public function index(Request $request): Response
    {
        $filters = $request->only('search', 'order_type', 'status', 'sort', 'direction', 'per_page');

        $orders = PlannedOrder::query()
            ->baseline()
            ->with('product:id,sku,name')
            ->filter($filters)
            ->when(
                $filters['sort'] ?? null,
                fn ($query) => TableQuery::applySort($query, $filters['sort'], $filters['direction'] ?? null, self::SORTABLE, 'need_by_date'),
                fn ($query) => $query->orderBy('need_by_date'),
            )
            ->paginate(TableQuery::perPage(isset($filters['per_page']) ? (int) $filters['per_page'] : null, 20))
            ->withQueryString()
            ->through(fn (PlannedOrder $o) => [
                'id' => $o->id,
                'plan_number' => $o->plan_number,
                'order_type' => $o->order_type,
                'product_sku' => $o->product?->sku,
                'product_name' => $o->product?->name,
                'qty' => (float) $o->qty,
                'need_by_date' => $o->need_by_date->toDateString(),
                'status' => $o->status,
            ]);

        return Inertia::render('PP/PlannedOrders/Index', [
            'orders' => $orders,
            'filters' => $filters,
        ]);
    }

    public function runMrp()
    {
        try {
            $run = $this->mrp->run();
        } catch (\RuntimeException $e) {
            return redirect()->route('pp.plannedOrders.index')->with('error', $e->getMessage());
        }

        $count = $run->plannedOrders()->count();

        return redirect()->route('pp.plannedOrders.index')->with('success', "MRP run complete — {$count} planned order(s) generated.");
    }

    public function release(PlannedOrder $plannedOrder)
    {
        try {
            $this->releaseService->release($plannedOrder);
        } catch (ValidationException $e) {
            return back()->withErrors($e->errors());
        }

        return redirect()->route('pp.plannedOrders.index')->with('success', "Planned order {$plannedOrder->plan_number} released.");
    }
}
