<!-- ponytail: Planning Exception Center (PP_SPECS.md §3M) — pure read model, no create/edit form.
     Rows are written by CapacityPlanService::checkOverload / MrpService's §3D/§3L checks. -->
<script setup lang="ts">
import { router } from '@inertiajs/vue3'
import AppLayout from '@/Components/layout/AppLayout.vue'
import PageHeader from '@/Components/layout/PageHeader.vue'
import DataTable, { type SortState } from '@/Components/tables/DataTable.vue'
import StatusBadge from '@/Components/feedback/StatusBadge.vue'
import { ref, watch } from 'vue'
import { debounce } from '@/Composables/debounce'

interface ExceptionRow {
  id: number
  exception_type: string
  severity: string
  subject_type: string
  subject_id: number
  subject_label: string
  detail: string | null
  status: string
  suggested_actions: string[]
  resolved_by: string | null
  resolved_at: string | null
  detected_at: string | null
}

interface PaginatedData<T> {
  data: T[]
  links: Array<{ url: string | null; label: string; active: boolean }>
  total: number
  from: number | null
  to: number | null
  per_page: number
}

const props = defineProps<{
  exceptions: PaginatedData<ExceptionRow>
  counts: Record<string, number>
  filters: { status?: string; exception_type?: string; sort?: string; direction?: string; per_page?: string }
  currentStatus: string
  currentType: string | null
}>()

const sort = ref<SortState>(
  props.filters.sort ? { key: props.filters.sort, direction: props.filters.direction === 'desc' ? 'desc' : 'asc' } : null,
)
const perPage = ref(Number(props.filters.per_page) || props.exceptions.per_page)

const columns = [
  { key: 'severity', label: 'Severity' },
  { key: 'exception_type', label: 'Type', sortable: true },
  { key: 'subject_label', label: 'Affected Order / Resource' },
  { key: 'detail', label: 'Detail' },
  { key: 'status', label: 'Status' },
  { key: 'detected_at', label: 'Detected At', sortable: true },
  { key: 'actions', label: 'Actions', align: 'right' as const },
]

const formatLabel = (value: string) => value.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())

const acknowledge = (id: number) => router.patch(route('pp.exceptions.acknowledge', id))
const resolve = (id: number) => router.patch(route('pp.exceptions.resolve', id))

const applyFilters = (overrides: Partial<{ status: string; exception_type: string | null }>) => {
  router.get(route('pp.exceptions.index'), {
    status: overrides.status ?? props.currentStatus,
    exception_type: 'exception_type' in overrides ? overrides.exception_type : props.currentType,
    sort: sort.value?.key,
    direction: sort.value?.direction,
    per_page: perPage.value,
  }, { preserveState: true, replace: true })
}

const filterStatus = (status: string) => applyFilters({ status })

// Clicking an already-active type chip clears the type filter (toggle), same UX as a tag filter.
const filterType = (type: string) => applyFilters({ exception_type: props.currentType === type ? null : type })

// A header-sort click or per-page change doesn't go through filterStatus/filterType, so it needs
// its own trip to the server — same pattern as ResourceGroups/Index.vue and
// ChangeoverMatrix/Index.vue's watch([...], debounce(...)).
watch([sort, perPage], debounce(() => applyFilters({}), 400))
</script>

<template>
  <AppLayout>
    <PageHeader
      title="Planning Exception Center"
      description="One row per detected planning condition — material shortages, capacity overloads, late orders — regenerated by each planning engine, never entered by hand (§3M)."
    />

    <div v-if="Object.keys(counts).length" class="mt-6 flex flex-wrap gap-3">
      <button
        v-for="(count, type) in counts"
        :key="type"
        type="button"
        class="flex items-center gap-2 rounded-md border px-3 py-2 text-sm transition"
        :class="props.currentType === type ? 'border-accent bg-accent/10' : 'border-border bg-surface-0 hover:bg-surface-50'"
        @click="filterType(String(type))"
      >
        <span class="text-signal-warning">⚠</span>
        <span class="font-semibold text-ink-900">{{ count }}</span>
        <span class="text-ink-600">{{ formatLabel(String(type)) }}</span>
      </button>
    </div>

    <div class="mt-6 flex items-center gap-2">
      <button
        v-for="s in ['open', 'acknowledged', 'resolved', 'all']"
        :key="s"
        type="button"
        class="px-3 py-1.5 text-xs font-medium rounded-md transition"
        :class="props.currentStatus === s ? 'bg-accent text-white' : 'bg-surface border border-border text-ink-700 hover:bg-surface-elevated'"
        @click="filterStatus(s)"
      >
        {{ formatLabel(s) }}
      </button>
    </div>

    <div class="mt-4">
      <DataTable
        :columns="columns"
        :items="exceptions.data"
        v-model:sort="sort"
        v-model:per-page="perPage"
        expandable
        sticky-header
        storage-key="pp.exceptions"
        :total="exceptions.total"
        :from="exceptions.from"
        :to="exceptions.to"
        :links="exceptions.links"
        empty-title="No exceptions"
        empty-description="Material shortages, capacity overloads, and late orders detected by MRP/RCCP will appear here."
      >
        <template #cell-severity="{ item }">
          <StatusBadge :status="(item as ExceptionRow).severity" />
        </template>
        <template #cell-exception_type="{ item }">
          <span class="text-sm font-medium text-ink-900">{{ formatLabel((item as ExceptionRow).exception_type) }}</span>
        </template>
        <template #cell-subject_label="{ item }">
          <span class="text-sm text-ink-700">{{ (item as ExceptionRow).subject_label }}</span>
        </template>
        <template #cell-detail="{ item }">
          <div class="max-w-md truncate text-sm text-ink-600" :title="(item as ExceptionRow).detail ?? ''">
            {{ (item as ExceptionRow).detail }}
          </div>
        </template>
        <template #cell-status="{ item }">
          <StatusBadge :status="(item as ExceptionRow).status" />
          <div v-if="(item as ExceptionRow).resolved_by" class="text-xs text-ink-500 mt-0.5">
            by {{ (item as ExceptionRow).resolved_by }} on {{ (item as ExceptionRow).resolved_at }}
          </div>
        </template>
        <template #cell-detected_at="{ item }">
          <div class="text-xs text-ink-700">{{ (item as ExceptionRow).detected_at }}</div>
        </template>
        <template #cell-actions="{ item }">
          <div v-if="(item as ExceptionRow).status !== 'resolved'" class="flex items-center justify-end gap-2">
            <template v-if="(item as ExceptionRow).status === 'open'">
              <button
                type="button"
                class="text-xs font-semibold text-signal-warning hover:underline"
                @click="acknowledge((item as ExceptionRow).id)"
              >
                Acknowledge
              </button>
              <span class="text-ink-300">|</span>
            </template>
            <button
              type="button"
              class="text-xs font-semibold text-signal-success hover:underline"
              @click="resolve((item as ExceptionRow).id)"
            >
              Resolve
            </button>
          </div>
          <div v-else class="text-xs text-ink-400 text-right">Done</div>
        </template>
        <template #row-detail="{ item }">
          <div class="bg-surface-50 p-4 text-sm">
            <div class="mb-2 font-semibold text-ink-700">Suggested Actions</div>
            <ul class="list-disc space-y-1 pl-5 text-ink-600">
              <li v-for="action in (item as ExceptionRow).suggested_actions" :key="action">{{ action }}</li>
            </ul>
          </div>
        </template>
      </DataTable>
    </div>
  </AppLayout>
</template>
