services:
  app:
    build:
      context: ./docker/php
    container_name: ${APP_CONTAINER_NAME:-qualiv_erp_app}
    restart: unless-stopped
    ports:
      - "${APP_PORT:-127.0.0.1:8085}:8000"
    volumes:
      - .:/var/www/html
      - ./storage/objects:/var/www/storage/nusaevo-erp
    env_file:
      - .env
    networks:
      - shared-infra

  queue:
    build:
      context: ./docker/php
    container_name: ${QUEUE_CONTAINER_NAME:-qualiv_erp_queue}
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    networks:
      - shared-infra
    command: php artisan queue:work --sleep=1 --tries=3 --timeout=0

networks:
  shared-infra:
    external: true
