<?php

namespace App\Modules\PP\Services;

use App\Modules\PP\Models\PpException;

/**
 * PP_SPECS.md §3M — the read-model side of the Planning Exception Center: record/acknowledge/
 * resolve plus the suggested-action list. Rows are written by the owning engine's own check
 * (CapacityPlanService::checkOverload, MrpService::checkLateOrders) — this service never scans
 * for conditions itself, per §3M "regenerated by each engine's constraint checks... not
 * maintained by hand".
 */
class PpExceptionService
{
    /** @return PpException the existing open row for this (type, subject) if one exists, else a new one */
    public function record(string $type, string $subjectType, int $subjectId, string $detail, string $severity = PpException::SEVERITY_MEDIUM): PpException
    {
        return PpException::query()->firstOrCreate([
            'exception_type' => $type,
            'subject_type' => $subjectType,
            'subject_id' => $subjectId,
            'status' => PpException::STATUS_OPEN,
        ], [
            'severity' => $severity,
            'detail' => $detail,
        ]);
    }

    public function acknowledge(PpException $exception): PpException
    {
        $exception->update(['status' => PpException::STATUS_ACKNOWLEDGED]);

        return $exception->refresh();
    }

    public function resolve(PpException $exception, int $userId): PpException
    {
        $exception->update([
            'status' => PpException::STATUS_RESOLVED,
            'resolved_by' => $userId,
            'resolved_at' => now(),
        ]);

        return $exception->refresh();
    }

    /**
     * §3M drill-down: "the action list is the same options §3F's overload rule already
     * enumerates, generalized per exception type" — source brief §8's list for capacity,
     * the analogous set for material/schedule conditions.
     *
     * @return list<string>
     */
    public function suggestedActions(PpException $exception): array
    {
        return match ($exception->exception_type) {
            PpException::TYPE_CAPACITY_OVERLOAD => [
                'Add overtime', 'Add a shift', 'Move production to another period',
                'Use an alternate resource', 'Outsource the excess load', 'Change quantity or due date',
            ],
            PpException::TYPE_MATERIAL_SHORTAGE, PpException::TYPE_LATE_PURCHASE => [
                'Expedite the purchase order', 'Use a substitute material',
                'Source from an alternate supplier', 'Split the lot', 'Push out the need-by date',
            ],
            PpException::TYPE_LATE_ORDER => [
                'Expedite the order', 'Split off an earlier partial lot',
                'Use overtime or an alternate resource to recover schedule',
                'Renegotiate the due date with the demand source',
            ],
            PpException::TYPE_MISSING_ROUTING, PpException::TYPE_RESOURCE_UNAVAILABLE, PpException::TYPE_MAINTENANCE_CONFLICT => [
                'Assign a routing or resource', 'Reschedule around the conflict', 'Use an alternate resource',
            ],
            default => ['Review manually'],
        };
    }
}
