<!--
  ponytail: Master Production Schedule grid (PP_SPECS.md §3C) — a pivot/matrix view (product ×
  period), not a record list, so this is a hand-rolled table using Tailwind utilities directly
  (CLAUDE.md §9C) rather than DataTable.vue, which is built for sortable/filterable/paginated
  lists of independent rows, not a fixed-column time-phased grid.
-->
<script setup lang="ts">
import { router, useForm } from '@inertiajs/vue3'
import { reactive, ref } from 'vue'
import { Lock, Unlock, Pin, PinOff, Eye, Trash2, Plus } from 'lucide-vue-next'
import AppLayout from '@/Components/layout/AppLayout.vue'
import PageHeader from '@/Components/layout/PageHeader.vue'
import Modal from '@/Components/Modal.vue'
import FormAsyncSearchableSelect from '@/Components/forms/FormAsyncSearchableSelect.vue'
import FormInput from '@/Components/forms/FormInput.vue'
import PrimaryButton from '@/Components/PrimaryButton.vue'
import SecondaryButton from '@/Components/SecondaryButton.vue'
import StatusBadge from '@/Components/feedback/StatusBadge.vue'
import EmptyState from '@/Components/feedback/EmptyState.vue'
import { useConfirm } from '@/Composables/useConfirmDialog'
import { formatNumber } from '@/Utils/formatters'

interface PlannedOrderSummary {
  id: number
  plan_number: string
  order_type: string
  qty: number
  status: string
}

interface MpsCell {
  id: number
  planned_qty: number
  is_frozen: boolean
  released_planned_order_id: number | null
  demand_qty: number
  is_shortfall: boolean
  available_qty: number
  capacity: number | null
  planned_order: PlannedOrderSummary | null
}

interface MpsRow {
  header_id: number
  product_id: number
  product_sku: string | null
  product_name: string | null
  cells: Record<string, MpsCell>
}

interface Period {
  start: string
  end: string
  label: string
}

const props = defineProps<{
  periods: Period[]
  rows: MpsRow[]
}>()

const { confirm } = useConfirm()

// --- Add product to grid ---
const showAddModal = ref(false)
const addForm = useForm({ product_id: null as number | null })
const submitAdd = () => addForm.post(route('pp.mps.store'), { onSuccess: () => { showAddModal.value = false; addForm.reset() } })

const removeRow = (row: MpsRow) => {
  confirm({
    title: `Remove ${row.product_sku ?? 'product'} from the MPS grid?`,
    description: 'Deletes this product’s MPS header and every period line. Planned orders already generated by MRP are not affected.',
    confirmText: 'Remove',
    variant: 'destructive',
    onConfirm: () => router.delete(route('pp.mps.destroy', row.header_id)),
  })
}

// --- Per-cell qty draft (only commits on blur/change, not every keystroke) ---
const qtyDrafts = reactive<Record<number, number>>({})
const draftFor = (cell: MpsCell) => qtyDrafts[cell.id] ?? cell.planned_qty
const setDraft = (cell: MpsCell, value: string) => { qtyDrafts[cell.id] = Number(value) }
const commitQty = (cell: MpsCell) => {
  const value = qtyDrafts[cell.id]
  if (value === undefined || value === cell.planned_qty) return
  router.patch(route('pp.mps.lines.update', cell.id), { planned_qty: value }, { preserveScroll: true })
}

const toggleFreeze = (cell: MpsCell) => router.patch(route('pp.mps.lines.freeze', cell.id), {}, { preserveScroll: true })

const toggleFirm = (cell: MpsCell) => {
  const url = cell.planned_order?.status === 'firmed'
    ? route('pp.mps.lines.unfirm', cell.id)
    : route('pp.mps.lines.firm', cell.id)
  router.patch(url, {}, { preserveScroll: true })
}

const releaseCell = (cell: MpsCell) => {
  confirm({
    title: 'Release this planned order?',
    description: cell.planned_order?.order_type === 'purchase'
      ? 'Creates a draft purchase requisition for this quantity.'
      : 'This order type cannot be released yet.',
    confirmText: 'Release',
    onConfirm: () => router.patch(route('pp.mps.lines.release', cell.id), {}, { preserveScroll: true }),
  })
}

// --- Drill-down detail panel ---
const detailCell = ref<MpsCell | null>(null)
const detailPeriod = ref<Period | null>(null)
const showDetail = (cell: MpsCell, period: Period) => { detailCell.value = cell; detailPeriod.value = period }
</script>

<template>
  <AppLayout>
    <PageHeader
      title="Master Production Schedule"
      description="Time-phased planner grid over §3B demand and §3D planned orders — freeze a period, firm or release its planned order."
    >
      <template #actions>
        <PrimaryButton type="button" @click="showAddModal = true">
          <Plus class="mr-1 h-4 w-4" /> Add Product
        </PrimaryButton>
      </template>
    </PageHeader>

    <EmptyState
      v-if="rows.length === 0"
      class="mt-6"
      title="No products on the MPS grid yet"
      description="Add a product to start planning its production schedule period by period."
      action-label="Add Product"
      @action="showAddModal = true"
    />

    <div v-else class="mt-6 overflow-x-auto rounded-lg border border-border">
      <table class="min-w-full divide-y divide-border text-sm">
        <thead class="bg-surface-50">
          <tr>
            <th class="sticky left-0 z-10 bg-surface-50 px-3 py-2 text-left font-medium text-ink-900">Product</th>
            <th
              v-for="period in periods"
              :key="period.start"
              class="min-w-[160px] px-3 py-2 text-left font-medium text-ink-900"
            >
              {{ period.label }}
            </th>
            <th class="px-3 py-2"></th>
          </tr>
        </thead>
        <tbody class="divide-y divide-border">
          <tr v-for="row in rows" :key="row.header_id">
            <td class="sticky left-0 z-10 bg-surface-0 px-3 py-2 align-top">
              <div class="font-mono text-xs text-ink-900">{{ row.product_sku }}</div>
              <div class="text-xs text-ink-600">{{ row.product_name }}</div>
            </td>
            <td v-for="period in periods" :key="period.start" class="px-3 py-2 align-top">
              <template v-if="row.cells[period.start]">
                <div class="space-y-1.5">
                  <FormInput
                    :model-value="draftFor(row.cells[period.start])"
                    type="number"
                    :disabled="row.cells[period.start].is_frozen"
                    @update:model-value="(v) => setDraft(row.cells[period.start], String(v))"
                    @change="commitQty(row.cells[period.start])"
                  />

                  <div class="flex items-center gap-1.5 text-ink-600">
                    <button
                      type="button"
                      class="rounded p-1 hover:bg-surface-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-accent"
                      :title="row.cells[period.start].is_frozen ? 'Unfreeze period' : 'Freeze period'"
                      @click="toggleFreeze(row.cells[period.start])"
                    >
                      <Lock v-if="row.cells[period.start].is_frozen" class="h-3.5 w-3.5" />
                      <Unlock v-else class="h-3.5 w-3.5" />
                    </button>

                    <button
                      v-if="row.cells[period.start].planned_order && row.cells[period.start].planned_order!.status !== 'released'"
                      type="button"
                      class="rounded p-1 hover:bg-surface-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-accent"
                      :title="row.cells[period.start].planned_order!.status === 'firmed' ? 'Unfirm planned order' : 'Firm planned order'"
                      @click="toggleFirm(row.cells[period.start])"
                    >
                      <PinOff v-if="row.cells[period.start].planned_order!.status === 'firmed'" class="h-3.5 w-3.5" />
                      <Pin v-else class="h-3.5 w-3.5" />
                    </button>

                    <button
                      v-if="row.cells[period.start].planned_order && row.cells[period.start].planned_order!.status !== 'released'"
                      type="button"
                      class="text-xs font-medium text-accent hover:underline"
                      @click="releaseCell(row.cells[period.start])"
                    >
                      Release
                    </button>

                    <button
                      type="button"
                      class="ml-auto rounded p-1 hover:bg-surface-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-accent"
                      title="View demand / order detail"
                      @click="showDetail(row.cells[period.start], period)"
                    >
                      <Eye class="h-3.5 w-3.5" />
                    </button>
                  </div>

                  <span v-if="row.cells[period.start].is_shortfall" class="inline-block">
                    <StatusBadge status="warning" label="Shortfall" />
                  </span>
                </div>
              </template>
            </td>
            <td class="px-3 py-2 align-top">
              <button
                type="button"
                class="rounded p-1 text-ink-600 hover:bg-surface-50 hover:text-signal-danger focus-visible:outline focus-visible:outline-2 focus-visible:outline-accent"
                title="Remove from grid"
                @click="removeRow(row)"
              >
                <Trash2 class="h-4 w-4" />
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Add product -->
    <Modal :show="showAddModal" max-width="md" @close="showAddModal = false">
      <div class="bg-surface-0 p-6">
        <h2 class="text-lg font-semibold text-ink-900">Add product to MPS grid</h2>
        <form class="mt-4 space-y-4" @submit.prevent="submitAdd">
          <FormAsyncSearchableSelect
            v-model="addForm.product_id"
            name="product_id"
            label="Product"
            api-entity="inventory_product"
            placeholder="Search SKU or name…"
            :error="addForm.errors.product_id"
            required
          />
          <div class="flex items-center justify-end gap-3 border-t border-border pt-4">
            <SecondaryButton type="button" @click="showAddModal = false">Cancel</SecondaryButton>
            <PrimaryButton type="submit" :disabled="addForm.processing">Add</PrimaryButton>
          </div>
        </form>
      </div>
    </Modal>

    <!-- Drill-down: Demand → Planned Production → Material → Capacity → Orders -->
    <Modal :show="detailCell !== null" max-width="md" @close="detailCell = null">
      <div v-if="detailCell && detailPeriod" class="bg-surface-0 p-6">
        <h2 class="text-lg font-semibold text-ink-900">{{ detailPeriod.label }}</h2>
        <dl class="mt-4 space-y-3 text-sm">
          <div class="flex items-center justify-between">
            <dt class="text-ink-600">Demand</dt>
            <dd class="font-mono text-ink-900">{{ formatNumber(detailCell.demand_qty) }}</dd>
          </div>
          <div class="flex items-center justify-between">
            <dt class="text-ink-600">Planned Production (this cell)</dt>
            <dd class="font-mono text-ink-900">{{ formatNumber(detailCell.planned_qty) }}</dd>
          </div>
          <div class="flex items-center justify-between">
            <dt class="text-ink-600">Material available</dt>
            <dd class="font-mono text-ink-900">{{ formatNumber(detailCell.available_qty) }}</dd>
          </div>
          <div class="flex items-center justify-between">
            <dt class="text-ink-600">Capacity</dt>
            <dd class="text-xs text-ink-600">Not available yet — Work Center Capacity (§3F) isn't built.</dd>
          </div>
          <div class="border-t border-border pt-3">
            <dt class="text-ink-600">Orders</dt>
            <dd class="mt-1">
              <template v-if="detailCell.planned_order">
                <div class="flex items-center justify-between">
                  <span class="font-mono text-xs text-ink-900">{{ detailCell.planned_order.plan_number }}</span>
                  <StatusBadge :status="detailCell.planned_order.status === 'released' ? 'active' : detailCell.planned_order.status" />
                </div>
                <div class="mt-1 text-xs text-ink-600">{{ detailCell.planned_order.order_type }} — {{ formatNumber(detailCell.planned_order.qty) }}</div>
              </template>
              <span v-else class="text-xs text-ink-600">No planned order in this period.</span>
            </dd>
          </div>
        </dl>
        <div class="mt-6 flex justify-end border-t border-border pt-4">
          <SecondaryButton type="button" @click="detailCell = null">Close</SecondaryButton>
        </div>
      </div>
    </Modal>
  </AppLayout>
</template>
