<!-- ponytail: Accounting §3M Coretax export — generate + list batches, inline form (no separate Create page since the form is this small). -->
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useForm, router } from '@inertiajs/vue3'
import AppLayout from '@/Components/layout/AppLayout.vue'
import PageHeader from '@/Components/layout/PageHeader.vue'
import FormSelect from '@/Components/forms/FormSelect.vue'
import FormSearchableSelect from '@/Components/forms/FormSearchableSelect.vue'
import PrimaryButton from '@/Components/PrimaryButton.vue'
import DataTable, { type SortState } from '@/Components/tables/DataTable.vue'
import { formatDate } from '@/Utils/formatters'

interface BatchRow {
  id: number
  batch_type: string
  masa_pajak: string | null
  record_count: number
  generated_by: string | null
  generated_at: string
}

const props = defineProps<{
  companies: Array<{ id: number; legal_name: string }>
  selectedCompanyId: number | null
  periods: Array<{ value: number; label: string }>
  batches: BatchRow[]
}>()

const search = ref('')
const sort = ref<SortState>(null)
const selected = ref<Array<string | number>>([])

const columns = [
  { key: 'batch_type', label: 'Batch Type', sortable: true },
  { key: 'masa_pajak', label: 'Masa Pajak', sortable: true },
  { key: 'record_count', label: 'Records', sortable: true, align: 'right' as const },
  { key: 'generated_by', label: 'Generated By' },
  { key: 'generated_at', label: 'Generated At', sortable: true },
  { key: 'actions', label: 'Actions', align: 'right' as const },
]

const batchTypeLabel = (t: string) => ({
  faktur_keluaran: 'Faktur Pajak Keluaran (output)',
  faktur_masukan: 'Faktur Pajak Masukan (input)',
  bukti_potong: 'Bukti Potong',
}[t] ?? t)

const filteredBatches = computed(() => {
  const q = search.value.trim().toLowerCase()
  if (!q) return props.batches
  return props.batches.filter((b) => batchTypeLabel(b.batch_type).toLowerCase().includes(q) || (b.masa_pajak ?? '').includes(q))
})

const switchCompany = (e: Event) => {
  const companyId = (e.target as HTMLSelectElement).value
  router.get(route('accounting.coretax-exports.index'), { company_id: companyId }, { preserveState: true })
}

const form = useForm({
  company_id: props.selectedCompanyId,
  tax_period_id: null as number | null,
  batch_type: 'faktur_keluaran',
})

const submit = () => form.post(route('accounting.coretax-exports.store'), { preserveScroll: true })
</script>

<template>
  <AppLayout>
    <PageHeader title="Coretax Exports" description="Structured-XML batches for bulk import into Coretax. Validate XML batch file before filing with DJP." />

    <div class="mt-6 space-y-6">
      <div class="rounded-lg border border-border bg-surface p-5 shadow-xs">
        <div class="mb-4 flex items-center gap-3">
          <label class="text-xs font-semibold text-ink-600">Company:</label>
          <select
            :value="selectedCompanyId"
            class="rounded-md border border-border bg-surface-0 px-3 py-1.5 text-sm font-medium text-ink-900 shadow-xs focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20"
            @change="switchCompany"
          >
            <option v-for="c in companies" :key="c.id" :value="c.id">{{ c.legal_name }}</option>
          </select>
        </div>

        <form class="grid grid-cols-1 items-end gap-4 sm:grid-cols-3" @submit.prevent="submit">
          <FormSearchableSelect v-model="form.tax_period_id" name="tax_period_id" label="Tax Period" :options="periods" :error="form.errors.tax_period_id" required />
          <FormSelect
            v-model="form.batch_type"
            name="batch_type"
            label="Batch Type"
            :options="[
              { label: 'Faktur Pajak Keluaran (output)', value: 'faktur_keluaran' },
              { label: 'Faktur Pajak Masukan (input)', value: 'faktur_masukan' },
              { label: 'Bukti Potong', value: 'bukti_potong' },
            ]"
            :error="form.errors.batch_type"
            required
          />
          <div class="pb-1">
            <PrimaryButton type="submit" :disabled="form.processing">Generate Export XML</PrimaryButton>
          </div>
        </form>
      </div>

      <DataTable
        :columns="columns"
        :items="filteredBatches"
        v-model:sort="sort"
        v-model:selected="selected"
        v-model:search="search"
        sticky-header
        storage-key="accounting.coretax-exports"
        search-placeholder="Search batch type or tax period…"
        export-filename="coretax-exports"
        empty-title="No Coretax export batches"
        empty-description="Generate a batch export for bulk Coretax filing."
      >
        <template #cell-batch_type="{ item }">
          <span class="font-medium text-ink-900">{{ batchTypeLabel((item as BatchRow).batch_type) }}</span>
        </template>

        <template #cell-masa_pajak="{ item }">
          <span class="font-mono text-xs text-ink-700">{{ (item as BatchRow).masa_pajak ?? '—' }}</span>
        </template>

        <template #cell-record_count="{ item }">
          <span class="font-mono text-xs font-semibold text-ink-900">{{ (item as BatchRow).record_count }}</span>
        </template>

        <template #cell-generated_by="{ item }">
          <span class="text-xs text-ink-700">{{ (item as BatchRow).generated_by ?? '—' }}</span>
        </template>

        <template #cell-generated_at="{ item }">
          <span class="font-mono text-xs text-ink-700">{{ formatDate((item as BatchRow).generated_at) }}</span>
        </template>

        <template #cell-actions="{ item }">
          <div class="flex items-center justify-end">
            <a
              :href="route('accounting.coretax-exports.download', (item as BatchRow).id)"
              class="text-xs font-semibold text-accent hover:underline focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent"
            >
              Download XML &darr;
            </a>
          </div>
        </template>
      </DataTable>
    </div>
  </AppLayout>
</template>
