<!-- ponytail: Accounting §3M Coretax export — generate + list batches, inline form (no separate Create page since the form is this small). -->
<script setup lang="ts">
import { useForm, router } from '@inertiajs/vue3'
import AppLayout from '@/Components/layout/AppLayout.vue'
import PageHeader from '@/Components/layout/PageHeader.vue'
import Panel from '@/Components/cards/Panel.vue'
import FormSelect from '@/Components/forms/FormSelect.vue'
import FormSearchableSelect from '@/Components/forms/FormSearchableSelect.vue'
import PrimaryButton from '@/Components/PrimaryButton.vue'

interface BatchRow {
  id: number
  batch_type: string
  masa_pajak: string | null
  record_count: number
  generated_by: string | null
  generated_at: string
}

const props = defineProps<{
  companies: Array<{ id: number; legal_name: string }>
  selectedCompanyId: number | null
  periods: Array<{ value: number; label: string }>
  batches: BatchRow[]
}>()

const switchCompany = (e: Event) => {
  const companyId = (e.target as HTMLSelectElement).value
  router.get(route('accounting.coretax-exports.index'), { company_id: companyId }, { preserveState: true })
}

const form = useForm({
  company_id: props.selectedCompanyId,
  tax_period_id: null as number | null,
  batch_type: 'faktur_keluaran',
})

const submit = () => form.post(route('accounting.coretax-exports.store'), { preserveScroll: true })

const batchTypeLabel = (t: string) => ({
  faktur_keluaran: 'Faktur Pajak Keluaran (output)',
  faktur_masukan: 'Faktur Pajak Masukan (input)',
  bukti_potong: 'Bukti Potong',
}[t] ?? t)
</script>

<template>
  <AppLayout>
    <PageHeader title="Coretax Exports" description="Structured-XML batches for bulk import into Coretax. The XML shape here is provisional — not yet verified against DJP's published import schema; a tax preparer should validate it before filing." />

    <Panel class="mt-6">
      <select
        :value="selectedCompanyId"
        class="mb-6 rounded-sm border border-border bg-surface-0 px-3 py-2 text-sm text-ink-900 shadow-sm focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20"
        @change="switchCompany"
      >
        <option v-for="c in companies" :key="c.id" :value="c.id">{{ c.legal_name }}</option>
      </select>

      <form class="mb-8 grid grid-cols-1 items-end gap-4 border-b border-border pb-6 sm:grid-cols-4" @submit.prevent="submit">
        <FormSearchableSelect v-model="form.tax_period_id" name="tax_period_id" label="Tax period" :options="periods" :error="form.errors.tax_period_id" required />
        <FormSelect
          v-model="form.batch_type"
          name="batch_type"
          label="Batch type"
          :options="[
            { label: 'Faktur Pajak Keluaran (output)', value: 'faktur_keluaran' },
            { label: 'Faktur Pajak Masukan (input)', value: 'faktur_masukan' },
            { label: 'Bukti Potong', value: 'bukti_potong' },
          ]"
          :error="form.errors.batch_type"
          required
        />
        <PrimaryButton type="submit" :disabled="form.processing">Generate export</PrimaryButton>
      </form>

      <table class="w-full text-sm">
        <thead>
          <tr class="border-b border-border text-left text-xs uppercase text-ink-600">
            <th class="py-2">Batch type</th>
            <th class="py-2">Masa pajak</th>
            <th class="py-2 text-right">Records</th>
            <th class="py-2">Generated by</th>
            <th class="py-2">Generated at</th>
            <th class="py-2 text-right">Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="b in batches" :key="b.id" class="border-b border-border hover:bg-surface-50">
            <td class="py-2 text-ink-900">{{ batchTypeLabel(b.batch_type) }}</td>
            <td class="py-2 text-ink-700">{{ b.masa_pajak ?? '—' }}</td>
            <td class="py-2 text-right text-ink-700">{{ b.record_count }}</td>
            <td class="py-2 text-ink-700">{{ b.generated_by ?? '—' }}</td>
            <td class="py-2 text-ink-700">{{ b.generated_at }}</td>
            <td class="py-2 text-right">
              <a :href="route('accounting.coretax-exports.download', b.id)" class="text-sm font-medium text-accent hover:underline">Download</a>
            </td>
          </tr>
          <tr v-if="!batches.length"><td colspan="6" class="py-6 text-center text-ink-600">No export batches generated yet.</td></tr>
        </tbody>
      </table>
    </Panel>
  </AppLayout>
</template>
