<!-- ponytail: Planned Orders listing (PP_SPECS.md §3D) — system-generated by MrpService::run() -->
<script setup lang="ts">
import { router } from '@inertiajs/vue3'
import PrimaryButton from '@/Components/PrimaryButton.vue'
import AppLayout from '@/Components/layout/AppLayout.vue'
import PageHeader from '@/Components/layout/PageHeader.vue'
import DataTable, { type FilterFieldDef, type SortState } from '@/Components/tables/DataTable.vue'
import StatusBadge from '@/Components/feedback/StatusBadge.vue'
import { ref, watch } from 'vue'
import { debounce } from '@/Composables/debounce'
import { useConfirm } from '@/Composables/useConfirmDialog'

interface PlannedOrderRow {
  id: number
  plan_number: string
  order_type: string
  product_sku: string | null
  product_name: string | null
  qty: number
  need_by_date: string
  status: string
}

interface PaginatedData<T> {
  data: T[]
  links: Array<{ url: string | null; label: string; active: boolean }>
  total: number
  from: number | null
  to: number | null
  per_page: number
}

const props = defineProps<{
  orders: PaginatedData<PlannedOrderRow>
  filters: { search?: string; order_type?: string; status?: string; sort?: string; direction?: string; per_page?: string }
}>()

const search = ref(props.filters.search ?? '')
const filters = ref({ order_type: props.filters.order_type ?? '', status: props.filters.status ?? '' })
const sort = ref<SortState>(
  props.filters.sort ? { key: props.filters.sort, direction: props.filters.direction === 'desc' ? 'desc' : 'asc' } : null,
)
const perPage = ref(Number(props.filters.per_page) || props.orders.per_page)

const filterFields: FilterFieldDef[] = [
  {
    key: 'order_type',
    label: 'Type',
    type: 'select',
    options: [
      { label: 'Production', value: 'production' },
      { label: 'Purchase', value: 'purchase' },
      { label: 'Transfer', value: 'transfer' },
    ],
  },
  {
    key: 'status',
    label: 'Status',
    type: 'select',
    options: [
      { label: 'Planned', value: 'planned' },
      { label: 'Released', value: 'released' },
      { label: 'Cancelled', value: 'cancelled' },
    ],
  },
]

const columns = [
  { key: 'plan_number', label: 'Plan #' },
  { key: 'order_type', label: 'Type' },
  { key: 'product_sku', label: 'SKU' },
  { key: 'product_name', label: 'Product' },
  { key: 'qty', label: 'Qty', align: 'right' as const, sortable: true },
  { key: 'need_by_date', label: 'Need by', sortable: true },
  { key: 'status', label: 'Status' },
  { key: 'actions', label: 'Actions', align: 'right' as const },
]

watch([search, filters, sort, perPage], debounce(() => {
  router.get(route('pp.plannedOrders.index'), {
    search: search.value,
    order_type: filters.value.order_type,
    status: filters.value.status,
    sort: sort.value?.key,
    direction: sort.value?.direction,
    per_page: perPage.value,
  }, { preserveState: true, replace: true })
}, 400))

const { confirm } = useConfirm()

const runMrp = () => {
  confirm({
    title: 'Run MRP now?',
    description: 'Regenerates every unreleased planned order from the current baseline demand and stock.',
    confirmText: 'Run MRP',
    onConfirm: () => router.post(route('pp.plannedOrders.runMrp')),
  })
}

const confirmRelease = (item: PlannedOrderRow | Record<string, unknown>) => {
  const row = item as PlannedOrderRow
  confirm({
    title: `Release ${row.plan_number}?`,
    description: row.order_type === 'purchase'
      ? 'Creates a draft purchase requisition for this quantity.'
      : 'This order type cannot be released yet.',
    confirmText: 'Release',
    onConfirm: () => router.patch(route('pp.plannedOrders.release', row.id)),
  })
}
</script>

<template>
  <AppLayout>
    <PageHeader
      title="Planned Orders"
      description="MRP output — production, purchase, and transfer suggestions netted from demand, on-hand stock, and safety stock."
    >
      <template #actions>
        <PrimaryButton type="button" @click="runMrp">Run MRP</PrimaryButton>
      </template>
    </PageHeader>

    <div class="mt-6 space-y-4">
      <DataTable
        :columns="columns"
        :items="orders.data"
        v-model:sort="sort"
        v-model:search="search"
        v-model:filters="filters"
        v-model:per-page="perPage"
        sticky-header
        storage-key="pp.plannedOrders"
        search-placeholder="Search SKU or name…"
        :filter-fields="filterFields"
        export-filename="pp-planned-orders"
        :total="orders.total"
        :from="orders.from"
        :to="orders.to"
        :links="orders.links"
        empty-title="No planned orders yet"
        empty-description="Run MRP to net current demand against stock and safety stock."
      >
        <template #cell-plan_number="{ item }">
          <span class="font-mono text-xs text-ink-900">{{ (item as PlannedOrderRow).plan_number }}</span>
        </template>
        <template #cell-order_type="{ item }">
          <span class="text-xs uppercase text-ink-600">{{ (item as PlannedOrderRow).order_type }}</span>
        </template>
        <template #cell-qty="{ item }">
          <span class="font-mono text-xs text-ink-600">{{ (item as PlannedOrderRow).qty }}</span>
        </template>
        <template #cell-status="{ item }">
          <StatusBadge :status="(item as PlannedOrderRow).status === 'released' ? 'active' : (item as PlannedOrderRow).status" />
        </template>
        <template #cell-actions="{ item }">
          <div class="flex items-center justify-end gap-3">
            <button
              v-if="(item as PlannedOrderRow).status === 'planned'"
              type="button"
              class="text-sm font-medium text-accent hover:underline focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent"
              @click="confirmRelease(item)"
            >
              Release
            </button>
            <span v-else class="text-xs text-ink-600">—</span>
          </div>
        </template>
      </DataTable>
    </div>
  </AppLayout>
</template>
